FROM golang:1.19 AS development
WORKDIR /go/src/github.com/escalopa/govisa/
COPY ./pkg /go/src/github.com/escalopa/govisa/
COPY ./telegram /go/src/github.com/escalopa/govisa/
COPY go.mod go.sum ./
RUN go mod download
RUN go install github.com/cespare/reflex@latest
CMD reflex -sr '\.go$' go run ./telegram/cmd/main.go

FROM golang:alpine AS builder
WORKDIR /go/src/github.com/escalopa/govisa/
COPY ./telegram ./telegram
COPY ./pkg ./pkg
COPY go.mod go.sum ./
RUN go build -o /go/bin/govisa-telegram ./telegram/cmd

FROM alpine:latest AS production
COPY --from=builder /go/bin/govisa-telegram /go/bin/govisa-telegram
ENTRYPOINT ["/go/bin/govisa-telegram"]
