version: '3.8'

services:
  api:
    container_name: govisa-api
    volumes:
      - .:/go/src/govisa/
    build:
      target: deployment
      dockerfile: ./deployments/Dockerfile-apit
    ports:
      - "8000:8000"
