version: '3.8'
services:
  api:
    image: 'dekuyo/govisa-bot:0.1'
    secrets:
      - govisa_bot_token
      - govisa_cache_url
      - govisa_secret_key
    environment:
      - BOT_TOKEN=/run/secrets/govisa_bot_token
      - REDIS_URL=/run/secrets/govisa_cache_url
      - ENCRYPT_KEY=/run/secrets/govisa_secret_key
      - TG_LOG_FILE=/home/ahmad/govisa/telegram.log
    extra_hosts:
      - "host.docker.internal:host-gateway"
secrets:
  govisa_bot_token:
    external: true
  govisa_cache_url:
    external: true
  govisa_secret_key:
    external: true
